# core/functions/tool_calls/native_tools.py
import json
import os
import difflib
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any, Dict, List, Optional

from qwen_agent.tools.base import BaseTool, register_tool
from qwen_agent.utils.utils import logger

from langchain_core.documents import Document
from retriever.sparse_retriever import KeywordBM25Retriever  # ← 前面给的轻封装BM25
from core.utils.format import DOC_TYPE_META
from core.utils.format import correct_json_format

# 可选：中文分词
def zh_preprocess(text: str):
    try:
        import re, jieba
        text = (text or "").strip()
        text = re.sub(r"\s+", " ", text)
        return list(jieba.cut(text, cut_all=False))
    except Exception:
        return (text or "").split()

def _meta_clean(m: Dict[str, Any]) -> Dict[str, Any]:
    # 只剔除 None 和 ""；保留 0 / False
    return {k: v for k, v in (m or {}).items() if v is not None and v != ""}

def _format_hits_mandatory(docs: List[Document]) -> str:
    lines: List[str] = []
    for i, d in enumerate(docs, 1):
        if lines:
            lines.append("")
            lines.append("---")
            lines.append("")
        lines.append(f"[{i}]")
        lines.append((d.page_content or "").strip())
        md = _meta_clean(d.metadata or {})
        if md:
            lines.append("metadata:")
            for k, v in md.items():
                lines.append(f"- {k}: {v}")
    return "\n".join(lines)


def _expand_bm25_query(query: str) -> str:
    raw = str(query or "").strip()
    if not raw:
        return raw

    extras: List[str] = []

    def _add(*terms: str) -> None:
        for term in terms:
            term = str(term or "").strip()
            if term and term not in raw and term not in extras:
                extras.append(term)

    if any(token in raw for token in ["一平", "每平", "平米", "每平方米", "平方米"]):
        _add("平米", "每平米", "元/平米", "万元/平米")
    if any(token in raw for token in ["房价", "房屋价格", "房屋售价"]):
        _add("房屋", "售卖广告", "原价", "现价")
    if any(token in raw for token in ["多少钱", "价格", "售价", "价钱"]):
        _add("多少元", "现价", "元")

    if not extras:
        return raw
    return raw + " " + " ".join(extras)


class _DocumentMappingIndex:
    """In-memory resolver for title/subtitle <-> document_id mapping."""

    def __init__(self, *, index_path: str, doc2chunks_path: Optional[str] = None, doc_type: str = "general"):
        self.index_path = index_path
        self.doc2chunks_path = doc2chunks_path
        self.doc_type = str(doc_type or "general").strip().lower() or "general"
        meta = DOC_TYPE_META.get(self.doc_type, DOC_TYPE_META.get("general", {}))
        self.title_field = str(meta.get("title", "title")).strip() or "title"
        self.subtitle_field = str(meta.get("subtitle", "subtitle")).strip() or "subtitle"

        # title_key = "<title> / <subtitle>" (subtitle 为空时退化为 title)
        self.title_key2document_ids: Dict[str, List[str]] = {}
        self.document_id2title_key: Dict[str, str] = {}
        self.document_id2title: Dict[str, str] = {}
        self.document_id2subtitle: Dict[str, str] = {}
        self._load()

    def _load_json(self, path: str, default: Any) -> Any:
        if not path or not os.path.exists(path):
            return default
        try:
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return default

    @staticmethod
    def _uniq_str_list(items: Any) -> List[str]:
        if not isinstance(items, list):
            return []
        out: List[str] = []
        seen = set()
        for x in items:
            s = str(x).strip()
            if not s or s in seen:
                continue
            seen.add(s)
            out.append(s)
        return out

    @staticmethod
    def _compose_title_key(title: str, subtitle: str) -> str:
        t = str(title or "").strip()
        st = str(subtitle or "").strip()
        if t and st:
            return f"{t} / {st}"
        return t or st

    @staticmethod
    def _norm(s: str) -> str:
        return " ".join(str(s or "").strip().lower().split())

    def _load(self) -> None:
        # 优先使用 doc2chunks（含 doc_type 对应 title/subtitle 字段）
        doc2chunks = self._load_json(self.doc2chunks_path or "", {})
        if isinstance(doc2chunks, dict) and doc2chunks:
            for source_doc, pack in doc2chunks.items():
                source_doc = str(source_doc).strip()
                if not source_doc:
                    continue

                md = (pack or {}).get("document_metadata") or {}
                if not isinstance(md, dict):
                    md = {}

                # Prefer doc-type-specific fields, but keep robust fallbacks for
                # older/newer metadata layouts generated by graph_builder.
                title = str(
                    md.get(self.title_field)
                    or md.get("title")
                    or md.get("doc_title")
                    or md.get("source_title")
                    or ""
                ).strip()
                subtitle = str(
                    md.get(self.subtitle_field)
                    or md.get("subtitle")
                    or md.get("sub_title")
                    or md.get("sub_scene_name")
                    or ""
                ).strip()
                title_key = self._compose_title_key(title, subtitle)

                if title_key:
                    self.title_key2document_ids.setdefault(title_key, [])
                    self.title_key2document_ids[title_key].append(source_doc)
                    self.document_id2title_key[source_doc] = title_key
                else:
                    # Keep exact reverse lookup available even if title fields are missing.
                    self.document_id2title_key[source_doc] = source_doc

                self.document_id2title[source_doc] = title
                self.document_id2subtitle[source_doc] = subtitle

            for k, ids in list(self.title_key2document_ids.items()):
                self.title_key2document_ids[k] = self._uniq_str_list(ids)
            return

        # 兜底：仅有 doc2chunks_index.json 时，至少保留 title_key <-> source_documents
        idx = self._load_json(self.index_path, {})
        if not isinstance(idx, dict):
            return
        t2k = idx.get("title2keys") or {}
        k2t = idx.get("key2title") or {}
        if isinstance(t2k, dict):
            for t, ids in t2k.items():
                title_key = str(t).strip()
                if not title_key:
                    continue
                clean_ids = self._uniq_str_list(ids)
                self.title_key2document_ids[title_key] = clean_ids
                for sid in clean_ids:
                    self.document_id2title_key[sid] = title_key
        if isinstance(k2t, dict):
            for sid, tk in k2t.items():
                s = str(sid).strip()
                title_key = str(tk).strip()
                if not s or not title_key:
                    continue
                self.document_id2title_key[s] = title_key
                self.document_id2title[s] = title_key
                self.document_id2subtitle[s] = ""

    def match_title_records(
        self,
        *,
        title: str = "",
        subtitle: str = "",
        fuzzy: bool = True,
        limit: int = 20,
    ) -> List[Dict[str, Any]]:
        title = str(title or "").strip()
        subtitle = str(subtitle or "").strip()
        if not title and not subtitle:
            return []

        records: Dict[str, Dict[str, Any]] = {}
        for sid, title_key in self.document_id2title_key.items():
            key = str(title_key or "").strip()
            if not key:
                continue
            rec = records.setdefault(
                key,
                {
                    "title_key": key,
                    "title": str(self.document_id2title.get(sid, "") or "").strip(),
                    "subtitle": str(self.document_id2subtitle.get(sid, "") or "").strip(),
                    "document_ids": [],
                },
            )
            rec["document_ids"].append(str(sid))

        def _field_score(query_text: str, target_text: str, *, threshold: float) -> float:
            q = self._norm(query_text)
            t = self._norm(target_text)
            if not q:
                return 0.0
            if not t:
                return -1.0
            if q == t:
                return 1.5
            if q in t or t in q:
                return 1.0
            if not fuzzy:
                return -1.0
            ratio = difflib.SequenceMatcher(None, q, t).ratio()
            return ratio if ratio >= threshold else -1.0

        scored: List[tuple[float, Dict[str, Any]]] = []
        for rec in records.values():
            title_score = _field_score(title, rec.get("title", ""), threshold=0.55) if title else 0.0
            subtitle_score = _field_score(subtitle, rec.get("subtitle", ""), threshold=0.5) if subtitle else 0.0

            if title and title_score < 0:
                continue
            if subtitle and subtitle_score < 0:
                continue

            score = 0.0
            if title:
                score += 0.7 * title_score
            if subtitle:
                score += 0.3 * subtitle_score
                if title and subtitle and subtitle_score > 0 and title_score > 0:
                    score += 0.1
            scored.append((score, rec))

        scored.sort(
            key=lambda x: (
                x[0],
                len(x[1].get("document_ids", [])),
                x[1].get("title_key", ""),
            ),
            reverse=True,
        )
        out: List[Dict[str, Any]] = []
        for _, rec in scored[: max(1, int(limit))]:
            clean = dict(rec)
            clean["document_ids"] = self._uniq_str_list(clean.get("document_ids", []))
            out.append(clean)
        return out

    def match_title_keys(self, query: str, *, fuzzy: bool = True, limit: int = 20) -> List[str]:
        q = str(query or "").strip()
        if not q:
            return []
        if q in self.title_key2document_ids:
            return [q]
        if not fuzzy:
            return []

        qn = self._norm(q)
        scored: List[tuple] = []
        for key in self.title_key2document_ids.keys():
            kn = self._norm(key)
            score = 0.0
            if qn in kn or kn in qn:
                score = 1.0
            else:
                ratio = difflib.SequenceMatcher(None, qn, kn).ratio()
                if ratio >= 0.55:
                    score = ratio
            if score > 0:
                scored.append((score, key))
        scored.sort(key=lambda x: x[0], reverse=True)
        return [k for _, k in scored[: max(1, int(limit))]]

    def match_document_ids(self, query: str, *, fuzzy: bool = True, limit: int = 20) -> List[str]:
        q = str(query or "").strip()
        if not q:
            return []
        if q in self.document_id2title_key:
            return [q]
        if not fuzzy:
            return []

        qn = self._norm(q)
        scored: List[tuple] = []
        for sid in self.document_id2title_key.keys():
            sn = self._norm(sid)
            score = 0.0
            if qn in sn or sn in qn:
                score = 1.0
            else:
                ratio = difflib.SequenceMatcher(None, qn, sn).ratio()
                if ratio >= 0.6:
                    score = ratio
            if score > 0:
                scored.append((score, sid))
        scored.sort(key=lambda x: x[0], reverse=True)
        return [sid for _, sid in scored[: max(1, int(limit))]]


class _BaseDocumentMappingTool(BaseTool):
    def __init__(self, *, index_path: str, doc2chunks_path: Optional[str] = None, doc_type: str = "general"):
        self.index = _DocumentMappingIndex(
            index_path=index_path,
            doc2chunks_path=doc2chunks_path,
            doc_type=doc_type,
        )
        self.doc_type = str(doc_type or "general").strip().lower() or "general"
        self.title_field = self.index.title_field
        self.subtitle_field = self.index.subtitle_field

    @staticmethod
    def _dedup_str_list(items: Any) -> List[str]:
        if isinstance(items, str):
            items = [items]
        if not isinstance(items, list):
            return []
        out: List[str] = []
        seen = set()
        for x in items:
            s = str(x).strip()
            if not s or s in seen:
                continue
            seen.add(s)
            out.append(s)
        return out


@register_tool("lookup_titles_by_document_ids")
class LookupTitlesByDocumentIDsTool(_BaseDocumentMappingTool):
    name = "lookup_titles_by_document_ids"
    description = (
        "把一个或多个 document_id 批量映射成可读的场次/章节标题。"
        "适合在拿到实体的 source_documents 或检索命中的 document_id 后，整理出场次列表。"
    )
    parameters = [
        {"name": "document_ids", "type": "array", "description": "待查询的 document_id 列表。", "required": True},
    ]

    def call(self, params: str, **kwargs) -> str:
        logger.info("🔎 调用 lookup_titles_by_document_ids")
        try:
            p: Dict[str, Any] = json.loads(params or "{}")
        except Exception as e:
            return f"参数解析失败：{e}"

        document_ids = self._dedup_str_list(p.get("document_ids"))
        if not document_ids:
            return "document_ids 不能为空"

        lines: List[str] = []
        hit = False
        for sid in document_ids:
            title = self.index.document_id2title.get(sid, "")
            subtitle = self.index.document_id2subtitle.get(sid, "")
            if not any([title, subtitle]):
                lines.append(f"document_id: {sid}")
                lines.append("title: not_found")
                lines.append("")
                continue
            hit = True
            lines.append(f"document_id: {sid}")
            lines.append(f"title: {title}")
            if subtitle:
                lines.append(f"subtitle: {subtitle}")
            lines.append("")

        if not hit:
            return "未找到任何 document_id 对应的 title/subtitle。"
        return "\n".join(lines).strip()


@register_tool("lookup_document_ids_by_title")
class LookupDocumentIDsByTitleTool(_BaseDocumentMappingTool):
    name = "lookup_document_ids_by_title"
    description = (
        "根据标题和副标题查询对应的 document_id。"
        "title 和 subtitle 均可选，且都支持模糊匹配，适合由场次/章节名称反查 source_documents。"
    )
    parameters = [
        {"name": "title", "type": "string", "description": "标题，可为空。", "required": False},
        {"name": "subtitle", "type": "string", "description": "副标题，可为空。", "required": False},
        {"name": "fuzzy", "type": "boolean", "description": "是否启用模糊匹配，默认 true。", "required": False},
        {"name": "limit", "type": "integer", "description": "最多返回多少个匹配到的文本块 document_id，默认 10。", "required": False},
    ]

    def call(self, params: str, **kwargs) -> str:
        logger.info("🔎 调用 lookup_document_ids_by_title")
        try:
            p: Dict[str, Any] = json.loads(params or "{}")
        except Exception as e:
            return f"参数解析失败：{e}"

        title = str(p.get("title", "")).strip()
        subtitle = str(p.get("subtitle", "")).strip()
        fuzzy = bool(p.get("fuzzy", True))
        limit = max(1, int(p.get("limit", 10) or 10))
        if not title and not subtitle:
            return "title 和 subtitle 不能同时为空"

        matched_records = self.index.match_title_records(
            title=title,
            subtitle=subtitle,
            fuzzy=fuzzy,
            limit=limit,
        )
        if not matched_records:
            query_text = title if title and not subtitle else f"{title} / {subtitle}".strip(" /")
            return f"未找到 title/subtitle 对应 document_id：{query_text}"

        lines: List[str] = []
        returned = 0
        for rec in matched_records:
            if rec.get("title"):
                lines.append(f"title: {rec['title']}")
            if rec.get("subtitle"):
                lines.append(f"subtitle: {rec['subtitle']}")
            lines.append("document_ids:")
            ids = self.index._uniq_str_list(rec.get("document_ids", []))
            remain = max(0, limit - returned)
            if remain <= 0:
                break
            for sid in ids[:remain]:
                lines.append(f"- {sid}")
                returned += 1
            lines.append("")
            if returned >= limit:
                break
        return "\n".join(lines).strip()


@register_tool("search_related_content")
class SearchRelatedContentTool(BaseTool):
    """
    Retrieve documents by document_id and extract query-related content in parallel.
    """

    name = "search_related_content"
    description = (
        "输入一个或多个 document_id 和 query，"
        "从 document-level 向量库读取原文后并发抽取与 query 直接相关的内容。"
        "仅返回提取结果非空的 document_id。"
    )
    parameters = [
        {
            "name": "document_ids",
            "type": "array",
            "description": "document_id 列表；兼容单个字符串。",
            "required": True,
        },
        {
            "name": "query",
            "type": "string",
            "description": "要抽取的目标问题/查询。",
            "required": True,
        },
        {
            "name": "max_length",
            "type": "integer",
            "description": "每个 document 的提取内容最大长度，默认 300。",
            "required": False,
        },
    ]

    def __init__(self, document_vector_store: Any, document_parser: Any, *, max_workers: int = 8):
        self.doc_vs = document_vector_store
        self.document_parser = document_parser
        self.max_workers = max(1, int(max_workers))

    @staticmethod
    def _dedup_ids(raw: Any) -> List[str]:
        if isinstance(raw, str):
            raw = [raw]
        if not isinstance(raw, list):
            return []
        out: List[str] = []
        seen = set()
        for x in raw:
            s = str(x).strip()
            if not s or s in seen:
                continue
            seen.add(s)
            out.append(s)
        return out

    @staticmethod
    def _parse_related_content(raw: str) -> str:
        try:
            data = json.loads(correct_json_format(raw))
            val = data.get("related_content", "")
            return val.strip() if isinstance(val, str) else ""
        except Exception:
            return ""

    def call(self, params: str, **kwargs) -> str:
        if str(os.environ.get("NKW_DISABLE_SEARCH_RELATED_CONTENT", "") or "").strip().lower() in {
            "1",
            "true",
            "yes",
            "on",
        }:
            return "（无）"
        logger.info("🔎 调用 search_related_content")
        try:
            p: Dict[str, Any] = json.loads(params or "{}")
        except Exception as e:
            return f"参数解析失败：{e}"

        document_ids = self._dedup_ids(p.get("document_ids"))
        query = str(p.get("query", "")).strip()
        max_length = p.get("max_length", 300)
        try:
            max_length = int(max_length)
            if max_length <= 0:
                max_length = 300
        except Exception:
            max_length = 300

        if not document_ids:
            return "document_ids 不能为空"
        if not query:
            return "query 不能为空"

        docs = self.doc_vs.search_by_document_ids(document_ids)
        id2parts: Dict[str, List[str]] = {}
        for d in docs or []:
            metadata = getattr(d, "metadata", {}) or {}
            did = str(metadata.get("document_id") or getattr(d, "id", "") or "").strip()
            txt = str(getattr(d, "content", "") or "").strip()
            if did and txt:
                id2parts.setdefault(did, []).append(txt)

        id2text = {
            did: "\n".join(parts).strip()
            for did, parts in id2parts.items()
            if parts
        }

        if not id2text:
            return "（无）"

        def _work(item: tuple[str, str]) -> tuple[str, str]:
            did, text = item
            try:
                raw = self.document_parser.search_related_content(
                    text=text,
                    goal=query,
                    max_length=max_length,
                )
                related = self._parse_related_content(raw)
                return did, related
            except Exception:
                return did, ""

        pairs = list(id2text.items())
        workers = min(self.max_workers, len(pairs))
        outputs: Dict[str, str] = {}
        with ThreadPoolExecutor(max_workers=max(1, workers)) as ex:
            futures = [ex.submit(_work, pair) for pair in pairs]
            for f in as_completed(futures):
                did, related = f.result()
                if related:
                    outputs[did] = related

        if not outputs:
            return "（无）"

        ordered_outputs = []
        for did in document_ids:
            txt = outputs.get(did)
            if txt:
                ordered_outputs.append((did, txt))
        lines = [f"{did}: {txt}" for did, txt in ordered_outputs]
        return "\n".join(lines)

@register_tool("bm25_search_docs")
class BM25SearchDocsTool(BaseTool):
    """
    基于 LangChain BM25 的稀疏检索（可选 rerank）
    - 初始化：documents(List[Document])、reranker(Optional)
    - 调用：params={"query": str, "k": int?}
    - 输出：返回检索命中的正文与 metadata，避免额外包裹抬头
    """

    name = "bm25_search_docs"
    description = "基于关键词和词面重合的 BM25 文本检索工具。适合查找专有名词、缩写全称、术语原文、固定表述，以及问题中出现过明确字词的证据段落。"
    parameters = [
        {"name": "query", "type": "string", "description": "检索文本，适合直接输入问题中的关键词、缩写、专有名词或想确认的原句片段", "required": True},
        {"name": "k", "type": "integer", "description": "返回条数（默认 10）", "required": False},
    ]

    def __init__(
        self,
        documents: List[Document],
        *,
        use_zh_preprocess: bool = True,
        k_default: int = 10,
    ):
        self.retriever = KeywordBM25Retriever(
            documents=documents,
            zh_preprocess=(zh_preprocess if use_zh_preprocess else None),
            k_default=k_default
        )

    def call(self, params: str, **kwargs) -> str:
        logger.info("🔎 调用 bm25_search_docs")
        try:
            p: Dict[str, Any] = json.loads(params or "{}")
        except Exception as e:
            return f"参数解析失败：{e}"

        query = str(p.get("query", "")).strip()
        if not query:
            return "query 不能为空"
        k = int(p.get("k", 10))
        expanded_query = _expand_bm25_query(query)

        try:
            hits = self.retriever.retrieve(query=expanded_query, k=k)
        except Exception as e:
            logger.exception("BM25 检索失败")
            return f"检索失败：{e}"

        if not hits:
            return "No results."

        return _format_hits_mandatory(hits)
